error: Report Secret Service errors
Don't crash when unable to save session; show in-app notifications when
either session saving or session restoring fails.

Fix #796. Partial fix #808, because this change won't tell the user how
to fix the error.